### ISSUE TITLE
node-sass will not build when installing using yarn

### ISSUE THREAD

**Issue by planktonic** [bitcrowd/bitstyles#296]
Running `yarn install` will fail during installing/building node-sass/node-gyp, whereas npm install completes the build correctly

```sh
gyp ERR!gyp build error 
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/darrencadwallader/Documents/bitcrowd/bitstyles/bitstyles/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/darrencadwallader/Documents/bitcrowd/bitstyles/bitstyles/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stackgyp     at ChildProcess.emit (events.js:203:13)
 gypERR!  ERR!System stack Darwin 18.7.0
     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! command \"/Users/darrencadwallader/.nvm/versions/node/v12.8.0/bin/node\" \"/Users/darrencadwallader/Documents/bitcrowd/bitstyles/bitstyles/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/darrencadwallader/Documents/bitcrowd/bitstyles/bitstyles/node_modules/cssnext/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/darrencadwallader/Documents/bitcrowd/bitstyles/bitstyles/node_modules/cssnext/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64\"
gyp ERR! cwd /Users/darrencadwallader/Documents/bitcrowd/bitstyles/bitstyles/node_modules/cssnext/node_modules/fsevents
gyp ERR!gyp  node -vERR! v12.8.0
 Systemgyp Darwin 18.7.0
 ERR! node-gyp -v v3.8.0
gypgyp  ERR!ERR! not ok command 
 \"/Users/darrencadwallader/.nvm/versions/node/v12.8.0/bin/node\" \"/Users/darrencadwallader/Documents/bitcrowd/bitstyles/bitstyles/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/darrencadwallader/Documents/bitcrowd/bitstyles/bitstyles/node_modules/cssnext/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/darrencadwallader/Documents/bitcrowd/bitstyles/bitstyles/node_modules/cssnext/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64\"
gyp ERR! cwd /Users/darrencadwallader/Documents/bitcrowd/bitstyles/bitstyles/node_modules/cssnext/node_modules/fsevents
gyp ERR! node -v v12.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/darrencadwallader/.nvm/versions/node/v12.8.0/bin/node /Users/darrencadwallader/Documents/bitcrowd/bitstyles/bitstyles/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/darrencadwallader/Documents/bitcrowd/bitstyles/bitstyles/node_modules/cssnext/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/darrencadwallader/Documents/bitcrowd/bitstyles/bitstyles/node_modules/cssnext/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/darrencadwallader/Documents/bitcrowd/bitstyles/bitstyles/node_modules/cssnext/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command \"/Users/darrencadwallader/.nvm/versions/node/v12.8.0/bin/node\" \"/Users/darrencadwallader/Documents/bitcrowd/bitstyles/bitstyles/node_modules/cssnext/node_modules/fsevents/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/darrencadwallader/Documents/bitcrowd/bitstyles/bitstyles/node_modules/cssnext/node_modules/fsevents
node-pre-gyp ERR! node -v v12.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
```

**Comment by planktonic** [comment]
This no longer an issue — node-sass is replaced by the dart-based sass
